// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccefhgceyufzzkdglyqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZWZoZ2NleXVmenprZGdseXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjY3MDMsImV4cCI6MjA2OTM0MjcwM30.L4NMdzoSfGB1TmoQoLRh3kvPBRZNFC7LXnP0L2hS3p8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});